INSERT INTO PESSOA (CPF ,NOME) VALUES ('123','Guilherme')
INSERT INTO PESSOA (CPF ,NOME) VALUES ('124','Joao')
INSERT INTO PESSOA (CPF ,NOME) VALUES ('125','Maria')
INSERT INTO PESSOA (CPF ,NOME) VALUES ('126','José')